version: "3"
services:
  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../QSIS:/code
      - ./nginx/log:/var/log/nginx
      - ./nginx/docker_nginx_qsis.conf:/etc/nginx/sites-available/docker_nginx_qsis.conf:ro
    networks:
      - qsis_net
    depends_on:
      - web
      - grafana

  web:
    container_name: "Django3-Vue"
    build: .
    init: true
    env_file:
      - .env
    # command: bash -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    command: bash -c "python manage.py makemigrations && python manage.py migrate --noinput && python manage.py collectstatic --noinput && uwsgi --ini  uwsgi.ini"
    volumes:
      - .:/code
      - /mnt/RESIS:/data
    ports:
      - "8001:8000"
      - "8003:8003"

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    user: "0"
    volumes:
      - ./grafana:/var/lib/grafana/ # Volume to persist configuration between restarts
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      #- ./grafana/provisioning:/usr/share/grafana/conf/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_DATABASE_HOST=influxdb:8086
      # - GF_DATABASE_NAME=station
    networks:
      - qsis_net
      - influxdb_net
    expose:
      - 3000

  influxdb2:
    image: influxdb:latest
    container_name: influxdb2
    networks:
      - influxdb_net
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=dmc
      - DOCKER_INFLUXDB_INIT_PASSWORD=yxul45j/vup7005
      - DOCKER_INFLUXDB_INIT_ORG=ORG
      - DOCKER_INFLUXDB_INIT_BUCKET=Bucket
      # 資料保存時間1week
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
    restart: always

networks:
  qsis_net:
    external: true
  influxdb_net:
